version: '3.5'

services:
  # portainer
  portainer:
    image: portainer/portainer
    container_name: portainer
    command: --admin-password '${PORTAINER_ADMIN_PASSWD_HASHED}'
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-v:/data
    networks:
      - portainer-network

  # yapi(2 services)
  yapi:
    image: jayfong/yapi:latest
    container_name: yapi-web
    environment:
      - YAPI_CLOSE_REGISTER=true
      - YAPI_DB_SERVERNAME=yapi-mongo
      - YAPI_DB_PORT=27017
      - YAPI_MAIL_ENABLE=false
      - YAPI_LDAP_LOGIN_ENABLE=false
      - YAPI_PLUGINS=[]
      - YAPI_ADMIN_ACCOUNT=${YAPI_ADMIN_EMAIL}
      - YAPI_ADMIN_PASSWORD=${YAPI_ADMIN_PASSWD}
      - YAPI_DB_DATABASE=${YAPI_DB_NAME}
    restart: unless-stopped
    depends_on:
      - yapi-mongo
    networks:
      - yapi-network
  yapi-mongo:
    image: mongo:latest
    container_name: yapi-mongo
    volumes:
      - yapi-mongodb-v:/data/db
    restart: unless-stopped
    networks:
      - yapi-network

  # caddy
  caddy:
    image: hectormolinero/caddy:latest
    container_name: caddy
    environment:
      ACME_AGREE: 'true'
      TLS_EMAIL: ${CADDY_TLS_EMAIL}
      ALICLOUD_ACCESS_KEY: ${CADDY_ALICLOUD_ACCESS_KEY}
      ALICLOUD_SECRET_KEY: ${CADDY_ALICLOUD_SECRET_KEY}
      DOMAIN_PORTAINER: ${CADDY_DOMAIN_PORTAINER}
      DOMAIN_YAPI: ${CADDY_DOMAIN_YAPI}
    restart: unless-stopped
    ports:
      - ${CADDY_PORT}:80
      - ${CADDY_SSL_PORT}:443
    volumes:
      - ./caddy/Caddyfile:/etc/Caddyfile:ro
      - ./caddy/caddyfile.d/:/etc/caddyfile.d/:ro
      - ./caddy/ssl/:/root/.caddy/
      - ./caddy/www/:/srv/:ro
      - ./caddy/logs/:/var/logs/
    depends_on:
      - portainer
      - yapi
    networks:
      - portainer-network
      - yapi-network

volumes:
  portainer-v:
    name: portainer-data
  yapi-mongodb-v:
    name: yapi-mongodb

networks:
  default:
    name: services-ali-network
  portainer-network:
    name: portainer-network
  yapi-network:
    name: yapi-network
